### ISSUE TITLE
Patch requests getting blocked by CORS

### ISSUE THREAD

**Issue by JoeSpizz** [learn-co-curriculum/react-hooks-fetch-crud-lab#7] opened 2022-08-21 21:59 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5301/assignments/180028?module_item_id=397392

### Concern

In both the CRUD putting it all together and the CRUD code-along I would get nasty  "cors" cross-origin errors that would collapse the site every time I attempted to PATCH data on the local db.json server. 
The tests would pass and it seems to be written properly but the site still crashed and I get nasty error messages.
<img width="461" alt="Screen Shot 2022-08-21 at 9 19 01 AM" src="https://user-images.githubusercontent.com/104811936/185812549-1c1a3f1d-b0d3-4794-a5d6-56c977433145.png">

screenshot is from code-along but same error occurs for both labs.  

### Suggested Changes

Tell me what is wrong with my system? I doubt this is a Flatiron issue but also CORS doesn't seem like it could ONLY affect me?

**Comment by lizbur10** [comment] 2022-08-22 19:37
Hi @JoeSpizz - Sorry to hear you've run into this problem! I am unable to reproduce the issue so I'm going to go ahead and close it. 

If you have not been able to resolve the problem, I suggest you use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

As always, thanks for contributing! 💙

**Closed by lizbur10** 2022-08-22 19:37 UTC
Labels: se curriculum
